<a href="https://colab.research.google.com/github/kashindra-mahato/SOC-support-system/blob/kashindra/firewall.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import pandas as pd
pd.options.display.max_colwidth = 100
pd.set_option('display.precision', 3)

###loading the dataset

In [ ]:
firewall0 = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/DATASET/log2.csv')

In [ ]:
firewall0.head()

Source Port  Destination Port  NAT Source Port  NAT Destination Port  \
0        57222                53            54587                    53   
1        56258              3389            56258                  3389   
2         6881             50321            43265                 50321   
3        50553              3389            50553                  3389   
4        50002               443            45848                   443   

  Action  Bytes  Bytes Sent  Bytes Received  Packets  Elapsed Time (sec)  \
0  allow    177          94              83        2                  30   
1  allow   4768        1600            3168       19                  17   
2  allow    238         118             120        2                1199   
3  allow   3327        1438            1889       15                  17   
4  allow  25358        6778           18580       31                  16   

   pkts_sent  pkts_received  
0          1              1  
1         10              9  
2          1              1  
3          8              7  
4         13             18

In [ ]:
firewall0.describe()

Source Port  Destination Port  NAT Source Port  NAT Destination Port  \
count    65532.000         65532.000        65532.000             65532.000   
mean     49391.969         10577.386        19282.973              2671.050   
std      15255.713         18466.027        21970.690              9739.162   
min          0.000             0.000            0.000                 0.000   
25%      49183.000            80.000            0.000                 0.000   
50%      53776.500           445.000         8820.500                53.000   
75%      58638.000         15000.000        38366.250               443.000   
max      65534.000         65535.000        65535.000             65535.000   

           Bytes  Bytes Sent  Bytes Received    Packets  Elapsed Time (sec)  \
count  6.553e+04   6.553e+04       6.553e+04  6.553e+04           65532.000   
mean   9.712e+04   2.239e+04       7.474e+04  1.029e+02              65.834   
std    5.618e+06   3.828e+06       2.463e+06  5.133e+03             302.462   
min    6.000e+01   6.000e+01       0.000e+00  1.000e+00               0.000   
25%    6.600e+01   6.600e+01       0.000e+00  1.000e+00               0.000   
50%    1.680e+02   9.000e+01       7.900e+01  2.000e+00              15.000   
75%    7.522e+02   2.100e+02       4.490e+02  6.000e+00              30.000   
max    1.269e+09   9.485e+08       3.209e+08  1.036e+06           10824.000   

        pkts_sent  pkts_received  
count   65532.000      65532.000  
mean       41.400         61.467  
std      3218.871       2223.332  
min         1.000          0.000  
25%         1.000          0.000  
50%         1.000          1.000  
75%         3.000          2.000  
max    747520.000     327208.000

In [ ]:
firewall0.Action.unique()

array(['allow', 'drop', 'deny', 'reset-both'], dtype=object)

In [ ]:
firewall0.isna().count()

Source Port             65532
Destination Port        65532
NAT Source Port         65532
NAT Destination Port    65532
Action                  65532
Bytes                   65532
Bytes Sent              65532
Bytes Received          65532
Packets                 65532
Elapsed Time (sec)      65532
pkts_sent               65532
pkts_received           65532
dtype: int64

In [ ]:
data = firewall0.drop(columns=['Action'], axis=1)

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(data)

StandardScaler()

In [ ]:
result = scaler.transform(data)

In [ ]:
result

array([[ 0.51325629, -0.56993668,  1.60688158, ..., -0.11847399,
        -0.01255093, -0.02719655],
       [ 0.45006636, -0.38927922,  1.68293804, ..., -0.16145495,
        -0.0097549 , -0.02359832],
       [-2.78658198,  2.15227224,  1.09155473, ...,  3.74650686,
        -0.01255093, -0.02719655],
       ...,
       [ 0.35914891, -0.54870834, -0.87767476, ..., -0.21766084,
        -0.01255093, -0.02764633],
       [ 0.35908336, -0.54870834, -0.87767476, ..., -0.21766084,
        -0.01255093, -0.02764633],
       [ 0.35888671, -0.54870834, -0.87767476, ..., -0.21766084,
        -0.01255093, -0.02764633]])

In [ ]:
df_result = pd.DataFrame(result)

In [ ]:
df_result.head()

0      1      2      3      4      5      6      7      8      9      10
0  0.513 -0.570  1.607 -0.269 -0.017 -0.006 -0.030 -0.020 -0.118 -0.013 -0.027
1  0.450 -0.389  1.683  0.074 -0.016 -0.005 -0.029 -0.016 -0.161 -0.010 -0.024
2 -2.787  2.152  1.092  4.893 -0.017 -0.006 -0.030 -0.020  3.747 -0.013 -0.027
3  0.076 -0.389  1.423  0.074 -0.017 -0.005 -0.030 -0.017 -0.161 -0.010 -0.024
4  0.040 -0.549  1.209 -0.229 -0.013 -0.004 -0.023 -0.014 -0.165 -0.009 -0.020

In [ ]:
num_cols = data.columns
df_result.columns = num_cols

In [ ]:
df_result.head()

Source Port  Destination Port  NAT Source Port  NAT Destination Port  \
0        0.513            -0.570            1.607                -0.269   
1        0.450            -0.389            1.683                 0.074   
2       -2.787             2.152            1.092                 4.893   
3        0.076            -0.389            1.423                 0.074   
4        0.040            -0.549            1.209                -0.229   

   Bytes  Bytes Sent  Bytes Received  Packets  Elapsed Time (sec)  pkts_sent  \
0 -0.017      -0.006          -0.030   -0.020              -0.118     -0.013   
1 -0.016      -0.005          -0.029   -0.016              -0.161     -0.010   
2 -0.017      -0.006          -0.030   -0.020               3.747     -0.013   
3 -0.017      -0.005          -0.030   -0.017              -0.161     -0.010   
4 -0.013      -0.004          -0.023   -0.014              -0.165     -0.009   

   pkts_received  
0         -0.027  
1         -0.024  
2         -0.027  
3         -0.024  
4         -0.020

In [ ]:
df_result.describe()

Source Port  Destination Port  NAT Source Port  NAT Destination Port  \
count    6.553e+04         6.553e+04        6.553e+04             6.553e+04   
mean     4.858e-16         8.548e-16       -2.195e-15             1.516e-16   
std      1.000e+00         1.000e+00        1.000e+00             1.000e+00   
min     -3.238e+00        -5.728e-01       -8.777e-01            -2.743e-01   
25%     -1.370e-02        -5.685e-01       -8.777e-01            -2.743e-01   
50%      2.874e-01        -5.487e-01       -4.762e-01            -2.688e-01   
75%      6.061e-01         2.395e-01        8.686e-01            -2.288e-01   
max      1.058e+00         2.976e+00        2.105e+00             6.455e+00   

           Bytes  Bytes Sent  Bytes Received    Packets  Elapsed Time (sec)  \
count  6.553e+04   6.553e+04       6.553e+04  6.553e+04           6.553e+04   
mean   7.503e-17  -5.222e-16      -3.271e-15  2.312e-15          -4.138e-15   
std    1.000e+00   1.000e+00       1.000e+00  1.000e+00           1.000e+00   
min   -1.728e-02  -5.832e-03      -3.034e-02 -1.985e-02          -2.177e-01   
25%   -1.728e-02  -5.831e-03      -3.034e-02 -1.985e-02          -2.177e-01   
50%   -1.726e-02  -5.824e-03      -3.031e-02 -1.965e-02          -1.681e-01   
75%   -1.715e-02  -5.793e-03      -3.016e-02 -1.887e-02          -1.185e-01   
max    2.259e+02   2.478e+02       1.302e+02  2.018e+02           3.557e+01   

       pkts_sent  pkts_received  
count  6.553e+04      6.553e+04  
mean   3.289e-16      8.222e-16  
std    1.000e+00      1.000e+00  
min   -1.255e-02     -2.765e-02  
25%   -1.255e-02     -2.765e-02  
50%   -1.255e-02     -2.720e-02  
75%   -1.193e-02     -2.675e-02  
max    2.322e+02      1.471e+02

In [ ]:
df_result['Action'] = firewall0.Action

In [ ]:
num_cols

Index(['Source Port', 'Destination Port', 'NAT Source Port',
       'NAT Destination Port', 'Bytes', 'Bytes Sent', 'Bytes Received',
       'Packets', 'Elapsed Time (sec)', 'pkts_sent', 'pkts_received'],
      dtype='object')

In [ ]:
# import plotly.express as px
# fig = px.scatter_matrix(df_result,dimensions=['Source Port', 'Destination Port', 'NAT Source Port',
#        'NAT Destination Port'], color='Action')
# fig.show()

In [ ]:
from sklearn.model_selection import train_test_split

###spliting data into train, test and validation

In [ ]:
x = df_result.drop(columns='Action')
y = df_result.Action
x_train, x_rem, y_train, y_rem = train_test_split(x, y, train_size=0.7) 

In [ ]:
x_valid, x_test, y_valid, y_test = train_test_split(x_rem, y_rem, test_size=0.7)

In [ ]:
display(x_train.shape, y_train.shape, x_test.shape, y_test.shape, x_valid.shape, y_valid.shape)

(45872, 11)

(45872,)

(13762, 11)

(13762,)

(5898, 11)

(5898,)

###stochastic gradient descent classification

In [ ]:
from sklearn.linear_model import SGDClassifier

sgd_clf = SGDClassifier()
sgd_clf.fit(x_train, y_train)

SGDClassifier()

In [ ]:
from sklearn.model_selection import cross_val_score
cross_val_score(sgd_clf, x_train, y_train, cv=3, scoring='accuracy')

array([0.98345432, 0.98391211, 0.98593852])

In [ ]:
from sklearn.model_selection import cross_val_predict
y_train_pred = cross_val_predict(sgd_clf, x_train, y_train, cv=3)

In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_train, y_train_pred)

array([[26232,   106,    71,     0],
       [   10,  9994,   492,     0],
       [    0,     0,  8930,     0],
       [    8,    29,     0,     0]])

In [ ]:
from sklearn.metrics import precision_score, recall_score, f1_score
precision_score(y_train, y_train_pred, average='weighted')

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


0.9842036390690831

In [ ]:
recall_score(y_train, y_train_pred, average='weighted')

0.9843913498430416

In [ ]:
f1_score(y_train, y_train_pred, average='weighted')

0.9840456219710771

In [ ]:
def prec_rec_f1(y_train, y_train_pred, average):
  p = precision_score(y_train, y_train_pred, average=average)
  r = recall_score(y_train, y_train_pred, average=average)
  f = f1_score(y_train, y_train_pred, average=average)
  print("precision score: ", p)
  print("\nrecall score: ", r)
  print("\nf1_score: ", f)

In [ ]:
y_valid_pred = sgd_clf.predict(x_valid)

In [ ]:
prec_rec_f1(y_valid, y_valid_pred, 'weighted')

precision score:  0.9829762515760797

recall score:  0.982875551034249

f1_score:  0.9826645379973394


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


###linear SVM classifier

In [ ]:
import numpy as np
from sklearn.pipeline import Pipeline
from sklearn.svm import LinearSVC

In [ ]:
svm_clf = Pipeline((
    ('scalar', StandardScaler()),
    ('linear_svc', LinearSVC(C=1, loss='hinge'))
))
svm_clf.fit(x_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/svm/_base.py:1208: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  ConvergenceWarning,


Pipeline(steps=[('scalar', StandardScaler()),
                ('linear_svc', LinearSVC(C=1, loss='hinge'))])

In [ ]:
y_valid_pred_svm = svm_clf.predict(x_valid)

In [ ]:
prec_rec_f1(y_valid, y_valid_pred_svm, 'weighted')

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


precision score:  0.9850230736561792

recall score:  0.9850796880298406

f1_score:  0.9848439406682341


###random forest classifier

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
rnd_clf = RandomForestClassifier(n_estimators=500, max_leaf_nodes=16, n_jobs=-1)
rnd_clf.fit(x_train, y_train)

RandomForestClassifier(max_leaf_nodes=16, n_estimators=500, n_jobs=-1)

In [ ]:
y_valid_pred_rf = rnd_clf.predict(x_valid)

In [ ]:
prec_rec_f1(y_valid, y_valid_pred_rf, 'weighted')

precision score:  0.997798038065856

recall score:  0.9983045100033909

f1_score:  0.998050706011122


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
